### ISSUE TITLE
multiprocessor problem and advice

### ISSUE THREAD

**Issue by StarsTesla** [deeplearning-wisc/MOOD#5]
After I download the code and model，then run the main.py，log error shows：
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "main.py", line 104, in <module>
        exitcode = _main(fd)val_loss, val_err1, val_err5 = validate(test_loader, model, criterion)

  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\spawn.py", line 114, in _main
  File "B:\git\MOOD\utils\msdnet_function.py", line 37, in validate
        prepare(preparation_data)for i, (input, target) in enumerate(val_loader):

  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
        _fixup_main_from_path(data['init_main_from_path'])return self._get_iterator()

  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
        run_name="__mp_main__")return _MultiProcessingDataLoaderIter(self)

  File "C:\ProgramData\Anaconda3\envs\torch37\lib\runpy.py", line 263, in run_path
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
        pkg_name=pkg_name, script_name=fname)w.start()

  File "C:\ProgramData\Anaconda3\envs\torch37\lib\runpy.py", line 96, in _run_module_code
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\process.py", line 112, in start
    mod_name, mod_spec, pkg_name, script_name)
self._popen = self._Popen(self)  File "C:\ProgramData\Anaconda3\envs\torch37\lib\runpy.py", line 85, in _run_code

      File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\context.py", line 223, in _Popen
exec(code, run_globals)
  File "B:\git\MOOD\main.py", line 104, in <module>
        return _default_context.get_context().Process._Popen(process_obj)val_loss, val_err1, val_err5 = validate(test_loader, model, criterion)

  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\context.py", line 322, in _Popen
  File "B:\git\MOOD\utils\msdnet_function.py", line 37, in validate
        return Popen(process_obj)for i, (input, target) in enumerate(val_loader):

  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    reduction.dump(process_obj, to_child)
return self._get_iterator()  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\reduction.py", line 60, in dump

  File "C:\ProgramData\Anaconda3\envs\torch37\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
        ForkingPickler(file, protocol).dump(obj)return _MultiProcessingDataLoaderIter(self)

BrokenPipeError  File "C:\ProgramData\Anaconda3\envs\torch37\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
: [Errno 32] Broken pipe
    w.start()
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Anaconda3\envs\torch37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

So I tried to make a change of the code like this:
`
def run():
    <include the all code of the main.py from the line " if 1:#load and test model" to "fig.savefig("Flops.pdf", bbox_inches='tight')">

if __name__ == '__main__':
    run()

`
probelm solved!

**Comment by myhakureimu** [comment]
Thank you for your suggestion!
